spring.application.name=sansaweigh
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/sansaweigh
spring.data.mongodb.database=sansaweigh

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# API Externa
external.scale.api.url=http://localhost:9090/api/scales

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html